[id="con_devfile_{context}"]
= Devfile

[role="_abstract"]

.What a devfile does for you

Devfiles are YAML files, and they simplify your development process. Devfiles capture instructions on how to set up your development environment and provide these instructions to your tools and IDE. The tools and IDE understand the instructions and support devfiles in order to take your development project from source code to a running application. By using devfiles, you can guarantee consistent patterns of behavior for applications written in different languages and using different tools. Devfiles also provide automation steps to your tools and IDE so that they can automate your current, manual processes. Using the recommended best practices from the devfile, the tools and IDE can: take in the repository hosting your application source code, build your code, run your application on your local container, and then deploy your application to cloud-native containers.

.Benefits of devfiles

With devfiles, you can make workspaces composed of multiple containers. In these containers, you can create any number of identical workspaces from the same devfile. If you create multiple workspaces, you can share your devfile with different teams. By sharing a single devfile across multiple teams, you can ensure that each team has the same user experience and the same build, run, deploy behaviors.

Use devfiles so that you have the following features:

* Guidance for using runtime images
* Example code
* Build and CI commands
* Deployment options

Use devfiles to help you with the following:

* Reduce the gap between development and deployment
* Find available devfile stacks or samples in a devfile registry
* Produce consistent build and run behaviors

.Roles that use devfiles

Stack providers use devfiles to develop their runtime stacks once and then use these runtime stacks across different tools. Therefore, with devfiles, you do not need to build and maintain custom development tools.

Tool providers use devfiles to build runtime support for each runtime. Now, the devfile runtime teams build and run applications on their servers, giving tool providers more time.

* To access the devfile stacks so you can begin creating container workspaces, see link:https://github.com/devfile/registry/tree/main/stacks[devfile registry stacks].
* To write your own devfile stack so you can begin using devfiles in your application development, see xref:authoring-stacks.adoc[].
* To migrate an existing devfile to the most updated version, see xref:migrating-to-devfile-v2.adoc[].
* To understand the schema attributes of devfiles, see xref:api-reference.adoc[].

.Additional resources

[role="_additional-resources"]

To ask questions, view open issues, raise concerns, or communicate directly with the devfile team, see the link:https://github.com/devfile/api[devfile GitHub repository].
