[id="con_devfile_{context}"]
= About devfiles

[role="_abstract"]

.How to use devfiles

Devfiles are YAML files, and they simplify your development process. In your IDE, devfiles tell you which best practices to apply to take your development project from source code to running application. Using the instructions given by devfiles, you can automate your current, manual processes. A devfile can take in the repository hosting your application source code. You can use the devfile to build your code, run your application on your local container, and then deploy your application to cloud-native containers.

.Features and benefits of devfiles

Devfiles give guidelines and instructions for enhanced development processes. Devfiles use the command line interface (CLI)  tool, `odo`, to build run, and deploy your application. By using odo, devfiles provide consistent patterns of behavior for applications written in different languages and create workspaces composed of multiple containers. In these containers, you can create any number of identical workspaces from the same devfile. If you create multiple workspaces, you can share your devfile with different teams. By sharing a single devfile across multiple teams, you can ensure that each team has the same user experience and the same build, run, deploy behaviors.

Using devfiles, you have the following features:

* Guidance for using runtime images
* Example code
* Build and CI commands
* Deployment options

Use devfiles to help you with the following:

* Reduce the gap between development and deployment
* Set up a registry for finding and hosting stacks
* Produce consistent build and run behaviors

See the following example of a simple devfile:

.A minimal devfile with one single project
====
[source,yaml]
----
schemaVersion: 2.1.0
metadata:
  name: petclinic-dev-environment
  version: 1.0.0
projects:
  - name: petclinic
    git:
      remotes:
        origin: "https://github.com/spring-projects/spring-petclinic.git"
      checkoutFrom:
        revision: main
----
====

.Roles that use devfiles

Stack providers use devfiles to develop their runtime stacks once and then use these runtime stacks across different tools. Therefore, with devfiles, you do not need to build and maintain custom development tools.

Tool providers use devfiles to build runtime support for each runtime. The devfile runtime teams build and run applications on their servers, giving you more time to work on your tools.

With devfiles, developers do not need to set up the environment for building and running their applications. Instead, you have the flexibility to use different tools, like Che and `odo`.

.How to work with devfiles

* To access the devfile stacks and images so you can begin creating container workspaces, see link:https://github.com/devfile/registry/tree/main/stacks[devfile registry stacks].
* To write your own devfile stack so you can begin using devfiles in your application development, see xref:authoring-stacks.adoc[].
* To migrate an existing devfile to the most updated version, see xref:migrating-to-devfile-v2.adoc[].
* To understand the schema attributes of devfiles, see xref:api-reference.adoc[].

.Additional resources

[role="_additional-resources"]

To ask questions, view open issues, raise concerns, or communicate directly with the devfile team, see the link:https://github.com/devfile/api[devfile GitHub repository].
