[id="con_devfile_{context}"]
= Devfile

[role="_abstract"]

Devfiles are YAML files that describe and define developer workspaces or cloud-native development environments. Devfiles also describe best practices for end-to-end application development and customize or extend the application development to fit a team's current development practices. Instead of forcing a new workflow or tools, devfiles provide instructions for automating manual processes.

<<<<<<< HEAD
Development tools consume devfiles and transform the definition into a cloud workspace composed of multiple containers and cloud-native resources. Also, users can create any number of identical workspaces from the same devfile. This way, different teams can use and share workspaces in various ways, including a devfile registry or together with the source code of a project.
=======
You can use devfiles to automate and simplify your development process. With devfiles, you record the instructions for configuring and running your build environment as a YAML-formatted text file. Then, optionally, you can distribute those devfiles to other build tools and IDEs that support devfiles. Finally, to automatically configure and build a running application from a development project, you run the devfile instructions. You can also use devfiles to provide consistent build processes across different languages and tools. 
>>>>>>> 34d94f6... sentence change and removed redudancy of software

A devfile includes:

* Guidance about runtime images
* Example code
* Build and CI commands
* Deployment options

Benefits of devfiles:

* Reducing the gap between development and deployment
* Having a registry for finding and hosting devfiles
* Producing consistent build and run behaviors
* Allowing easy devfile customization

.Who can use devfiles?

Stack providers use devfiles to develop their runtime stacks once and then use these runtime stacks across different tools. Therefore, with devfiles, stack providers do not need to build and maintain custom development tools.

Tool providers use devfiles to build runtime support for each runtime. Now, the devfile runtime teams build and run applications on their servers, giving tool providers more time.

Developers use devfiles to focus only on developing their applications. With devfiles, developers do not need to set up the environment for building and running their applications. Instead, developers have the flexibility to use different tools, like Che and odo.

.Additional resources

[role="_additional-resources"]

* Example tool: link:https://developers.redhat.com/products/odo/overview[odo]
* Devfile terminologies: xref:api-reference.adoc[]
* Work with devfiles: xref:authoring-stacks.adoc[]
* Update devfiles: xref:migrating-to-devfile-v2.adoc[]
* Learn more about devfiles: xref:devfile-samples.adoc[]
* Devfile registry: link:https://registry.devfile.io/[registry.devfile.io]
* Devfile registry source: link:https://github.com/devfile/registry[devfile/registry]
