[id="proc_adding-container-component-to-a-devfile_{context}"]
= Adding `container` components to a devfile

[role="_abstract"]
Use devfile components to define a container image-based configuration of a container in your workspace. The devfile component is identified by its image and can contain one or more components of the `container` type. Use the `container` type of components to incorporate custom tools into your workspace.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-components-to-a-devfile.adoc[]

.Procedure

. Define a component using the type `container`.
+
.A `container` component
[source,yaml]
----
 components:
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      volumeMounts:
        - name: mavenrepo
          path: /root/.m2
       env:
         - name: ENV_VAR
           value: value
       endpoints:
         - name: maven-server
           targetPort: 3101
           protocol: https
           secure: 'true'
           exposure: public
       memoryLimit: 1536M
       command: ['tail']
       args: ['-f', '/dev/null']
----
+
.A minimal `container` component
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
    name: mydevfile
components:
  - name: go
    container:
      image: golang
      memoryLimit: 512Mi
      command: ['sleep', 'infinity']
----
+
Specify the type of component with the `container` attribute. Use the `image` attribute to name the image used for the component. When naming the `image` attribute, use Docker naming conventions; for instance, the `image` attribute in the preceding example is equal to `docker.io/library/golang:latest`.
+
With a `container` component, you can augment the image with additional resources and information. You need these recourses and information so you can integrate the tools provided by the devfile image. 

. Mounting project sources
+
For the `container` component to have access to the project sources, you must set the `mountSources` attribute to `true`.
+
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
    name: mydevfile
components:
  - name: go
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
----
+
The source is mounted on a location stored in the `PROJECTS_ROOT` environment variable that is made available in the running container of the image. This location defaults to `/projects`. If `sourceMapping` is defined in the container, the location overrides the `PROJECT_ROOT` value and mounts the source to the path defined by `sourceMapping`.

. Container Entrypoint
+
Use the `command` attribute of the `container` to modify the `entrypoint` command of the container created from the image. In devfiles, the container runs indefinitely, so you can consistently connect to it and execute commands in it. The availability of the `sleep` command and the support for the `infinity` argument depend on the base image used in the particular images. Therefore, devfiles cannot automatically include these commands.

[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
