[id="proc_migrating-plug-ins_{context}"]
= Migrating plug-ins

[role="_abstract"]
This section describes how to migrate plug-ins to devfile v2.x. There ARE major changes about the definition of plugins in a devfile. Plugins are now specified using a devfile. A plugin specified in a v1.0 meta.yaml will NOT work as it is in a devfile v2.x.

Additionally, v2.x devfiles include the following new features:

* Parents allow users to reuse an existing devfile and partially replace plug-in functionality.
* Eclipse Che IDEs and their tooling can be specified as attributes in a v2.x devfile or in a distinct YAML file, for example: `.che/che-editor.yaml` or `.che/che-theia-plugin.yaml`.


[role="_additional-resources"]
.Additional resources

To learn more about plug-ins in v2.x devfiles, go to the GitHub issues on the following topics:

* link:https://github.com/eclipse/che/issues/18669[Devfile plugins not suited to specify Che-Theia plugins].
* link:https://github.com/eclipse/che/issues/18668[Che editors and Che-Theia plugins support in devfile v2.x].
* link:https://github.com/devfile/api/issues/364[Plugins' replacement].
* link:https://github.com/devfile/api/issues/31[Better plugin mechanism].
