[id="proc_limiting-resources-usage_{context}"]
= Limiting resources usage

[role="_abstract"]


.Procedure

. Specify container memory limit for components
+
To specify a container(s) memory limit for `container`, `plugin`, use the `memoryLimit` parameter:
+
.Specify container memory limit for components
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      id: eclipse/che-machine-exec-plugin/0.0.1
      memoryLimit: 1Gi
   -   name: maven
     container:
      image: eclipe/maven-jdk8:latest
      memoryLimit: 512M
----
====
+
This limit will be applied to every container of the given component.
+
For `plugin` components, RAM limits can be described in the plug-in descriptor file, typically named `meta.yaml`.
+
If none of them are specified, system-wide defaults will be applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB]` system property).


. Specify container memory request for components
+
To specify a container(s) memory request for `plugin` use the `memoryRequest` parameter:
+
.Specify container memory request for components
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      id: eclipse/che-machine-exec-plugin/0.0.1
      memoryLimit: 1Gi
      memoryRequest: 512M
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      memoryLimit: 512M
      memoryRequest: 256M
----
====
+
This limit will be applied to every container of the given component.
+
For `plugin` components, RAM requests can be described in the plug-in descriptor file, typically named `meta.yaml`.
+
If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__REQUEST__MB]` system property).


. Specify container CPU limit for components
+
To specify a container(s) CPU limit for `plugin` or `container` use the `cpuLimit` parameter:
+
.Specify container CPU limit for components
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
       id: eclipse/che-machine-exec-plugin/0.0.1
       cpuLimit: 1.5
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      cpuLimit: 750m
----
====
+
This limit will be applied to every container of the given component.
+
For the `plugin` components, CPU limits can be described in the plug-in descriptor file, typically named `meta.yaml`.
+
If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES]` system property).


. Specify container CPU request for components
+
To specify a container(s) CPU request for `plugin` or `container` use the `cpuRequest` parameter:
+
.Specify container CPU request for components
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      id: eclipse/che-machine-exec-plugin/0.0.1
      cpuLimit: 1.5
      cpuRequest: 0.225
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      cpuLimit: 750m
      cpuRequest: 450m
----
====
+
This limit will be applied to every container of the given component.
+
For the `pugin` component type, CPU requests can be described in the plug-in descriptor file, typically named `meta.yaml`.
+
If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES]` system property).
