[id="proc_limiting-resources-usage_{context}"]
= Limiting resources usage

[role="_abstract"]
This section describes how to limit resource use in devfiles.

.Procedure

. Specify container memory limit and memory request for components
+
To specify a container memory limit for `container`, use the `memoryLimit` parameter. To specify a container memory request, use the `memoryRequest` parameter:
+
.Specify container memory limit and memory request for components
====
[source,yaml]
----
  components:
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      memoryLimit: 512M
      memoryRequest: 256M
----
====
+
This limit applies to every container of the given component.
+

If they are not specified, the values are undetermined, meaning they may or may not be inferred from the application that consumes the devfile or from Kubernetes.
+

. Specify container CPU limit and container CPU request for components
+
To specify a container CPU limit for `container`, use the `cpuLimit` parameter. To specify a container CPU request for `container`, use the `cpuRequest` parameter:
+
.Specify container CPU limit and CPU request for components
====
[source,yaml]
----
  components:
   - name: maven
     container:
      image: eclipe/maven-jdk8:latest
      cpuLimit: 750m
      cpuRequest: 450m
----
====
+
This limit applies to every container of the given component.
+

If they are not specified, the values are undetermined, meaning they may or may not be inferred from the application that consumes the devfile or from Kubernetes.
+
