[id="deploying-devfile-registry_{context}"]
= Deploying a devfile registry with operator lifecycle manager

[role="_abstract"]
When you have operator lifecycle manager (OLM) installed on your cluster, use the devfile registry operator to install and deploy a devfile registry.

.Procedure
..Installing the devfile registry operator
. Install link:https://github.com/operator-framework/operator-lifecycle-manager[OLM].
. Download the link:https://mirror.openshift.com/pub/openshift-v4/clients/operator-sdk/latest/[operator-sdk CLI].
. Run `operator-sdk run bundle quay.io/devfile/registry-operator-bundle:next` to install the operator-sdk CLI.

..Deploying the devfile registry
. On an OpenShift cluster, run:
+
====
----
$ cat <<EOF | oc apply -f -
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
Metadata:
  name: devfile-registry
spec:
  devfileIndexImage: quay.io/devfile/devfile-index:next
EOF
----
====
+
. On a Kubernetes cluster, set the k8s.ingressDomain field:
+
====
----
$ cat <<EOF | kubectl apply -f -
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  		     name: devfile-registry
spec:
  devfileIndexImage: quay.io/devfile/devfile-index:next
 		 tls:
    enabled: false
  k8s:
    ingressDomain: $INGRESS_DOMAIN
EOF
----
====
+

Note: whether you are on the OpenShift or Kubernetes cluster, if you are deploying your own devfile registry, change the `devfileIndexImage` field to the container image that you built.

[role="_additional-resources"]
.Additional resources

* For information on installing the devfile registry operator, see link:https://github.com/devfile/registry-operator[devfile-registry-operator].
* For information on installing OLM on your Kubernetes cluster, see the link:https://olm.operatorframework.io/docs/getting-started/[OLM quick start guide].
