[id="proc_adding-plugin-component-to-a-devfile_{context}"]
= Adding `plugin` component to a devfile

[role="_abstract"]
This section describes how to add a `plugin` component to a devfile.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-components-to-a-devfile.adoc[]

.Procedure

. Define a component using the type `plugin`.

. Define the `id` attribute. It is slash-separated publisher, name and version of plug-in from the Plug-in registry. List of available {prod-short} plug-ins and more information about registry can be found in the link:https://github.com/eclipse/che-plugin-registry[{prod-short} plug-in registry] GitHub repository.
+
.A devfile defining a plug-in `id`
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      id: machine-exec-plugin/0.0.1
----
====

. Optionally, specify an alternative component registry using the `registryUrl` parameter:
+
.A devfile defining a plug-in `id` and an alternative component registry
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      id: machine-exec-plugin/0.0.1
      registryUrl: https://my-customregistry.com
----
====

. Optionally, provide a direct link to the component descriptor (typically named `meta.yaml`) using the `reference` attribute, instead of using the `id`.
+
.A devfile defining a plug-in with a direct link to the component descriptor
====
[source,yaml]
----
  components:
   - name: exec-plugin
     plugin:
      reference: https://raw.githubusercontent.com.../plugin/1.0.1/meta.yaml
----
====
+
NOTE: It is impossible to mix the `id` and `reference` fields in a single component definition; they are mutually exclusive.


. Optionally, provide plugin component configuration using the `preferences` attribute
+
.Configuring JVM using plug-in preferences
====
[source,yaml]
----
  id: redhat/java/0.38.0
  plugin:
    preferences:
       java.jdt.ls.vmargs: '-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication'
----
====
+
.Configuring preferences as an array:
====
[source,yaml]
----
  id: redhat/java/0.38.0
  plugin:
    preferences:
      go.lintFlags: ["--enable-all", "--new"]
----
====


[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
