[id="proc_adding-a-kubernetes-or-openshift-component-to-a-devfile_{context}"]
= Adding a Kubernetes or OpenShift component to a devfile

[role="_abstract"]
You can add either a `kubernetes` or `openshift` component to a devfile.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-components-to-a-devfile.adoc[]

.Procedure

. Define a component using the `kubernetes` or `openshift` property.

. Provide the content through the `uri` or `inlined` property.
+
.Adding an `openshift` component using the `uri` property
====
[source,yaml]
----
  components:
    - name: mysql
      openshift:
        uri: petclinic.yaml
----
====
+
.Adding a `kubernetes` component using the `inlined` property
====
[source,yaml]
----
  components:
  - name: myk8deploy
    kubernetes:
      inlined: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
        spec:
          template:
            spec:
              containers:
              - name: job
                image: myimage
                command: ["some",  "command"]
              restartPolicy: Never
----
====
+
. Specify the endpoint through the endpoint property with `kubernetes` or `openshift` components.

. By default `kubernetes` or `openshift` components are not going to be deployed. Specify `deployByDefault=true` if you want to apply the component at start up.

. Associate `kubernetes` or `openshift` components with `Apply` commands wth `deploy` command group kind. If the `kubernetes` or `openshift` component uses an image built by an image component defined in the devfile, you can create a composite `deploy` command to build the image and deploy the Kubernetes or openshift component. For more information on `deploy` commands, see xref:adding-a-command-group-to-a-devfile.adoc[]
+
