[id="proc_referring-to-a-parent-devfile-in-a-devfile_{context}"]
= Referring to a parent devfile in a devfile

[role="_abstract"]
This section describes how to designate a parent devfile to a given devfile. If you designate a parent devfile, the given devfile inherits all its behavior from its parent.  Still, you can use the child devfile to override certain content from the parent devfile. If you override the correct content, you can reuse the same parent devfile in multiple other devfiles. If you do reuse a parent devfile, the parent turns into a stack that is used in multiple other devfiles.

.Prerequisites

* Define the `schemaVersion` to v2.x. If you need to define your `schemaVersion`, go to xref:adding-schema-version-to-a-devfile.adoc[].
* Define a name for the devfile. If you need to define a name for your devfile, go to xref:adding-a-name-to-a-devfile.adoc[].


.Procedure

You can refer to a parent devfile in three different ways:

* `registry`
* `uri`
* `kubernetes`

+
.Parent referred by registry
====
Using its `id` if it has been published in a registry.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    id: redhat/nodejs
    registry: https://devfile-registry.io/
----
====
+
.Parent referred by uri
====
Using the URI if it has been published on a static http server (like gist or pastebin).

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    uri: https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/nodejs/devfile.yaml
----
====
+
.Parent identified by a Kubernetes resource
====
Using a Kubernetes resource name and namespace if it has been deployed on a Kubernete cluster.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    kubernetes:
        name: mydevworkspacetemplate
        namespace: mynamespace
----
====

[role="_additional-resources"]
.Additional resources

For more information on referring to parent devfiles, go to the following topics:

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
