[id="proc_refering-to-a-parent-devfile-in-a-devfile_{context}"]
= Refering to a parent devfile in a devfile

[role="_abstract"]
You can designate a parent devfile to a given devifle. If you designate a parent devfile, the given devfile inherits all its behavior from its parent.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]


This section describes how to specify a parent devfile. You can choose a devfile and refer to another devfile as its parent. If you specify a parent, the child devfile inherits all its behavior from its parent devfile. Still, you can use the child devfile to override certain content from the parent devfile. If you override the correct content, you can reuse the same parent devfile in multiple other devfiles. If you do reuse a parent devfile, the parent turns into a stack that is used in multiple other devfiles.

.Procedure

You can refer to a parent devfile in three different ways:

* registry
* uri
* kubernetes

.Parent referred by registry
====
Use the `id` if it has been published in a registry.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    id: redhat/nodejs
    registry: https://devfile-registry.io/
----
====

.Parent referred by uri
====
Use the URI if it has been published on a static http server like gist or pastebin.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
<<<<<<< HEAD
    uri: https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/nodejs/devfile.yaml
=======
    id: redhat/nodejs/11.6
    uri: https://raw.githubusercontent.com/devfile/registry/master/stacks/nodejs/devfile.yaml
>>>>>>> c68d47f... brought back the procedures, updated links, more changes to content for consistency and style guide
----
====

.Parent identified by a Kubernetes resource
====
Use a Kubernetes resource name and namespace if it has been deployed on a Kubernetes cluster.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    kubernetes:
        name: mydevworkspacetemplate
        namespace: mynamespace
----
====

[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
