[id="proc_devfile-quick-reference_{context}"]
= Devfile quick reference

[role="_abstract"]
This page describes devfile properties and requirements for using them.

== schemaVersion

[source,yaml]
----
v2.0
---
schemaVersion: 2.0.0
----

[horizontal]
Key:: schemaVersion
Type:: string
Required:: yes
Description:: v2.0.0 of the schema

For more information about the schemaVersion in devfiles, see: xref:migrating-schema-version.adoc[].

== metadata

[source,yaml]
----
v2.0
---
metadata:
  name: devfile-sample
  version: 2.0.0
----

[horizontal]
Key:: metadataObject
Type:: metadataObject
Required:: no
Description:: metadata to be used

For more information about the metadata in devfiles, see: xref:adding-projects-to-a-devfile.adoc[].

== starterProjects

[source,yaml]
----
v2.0
---
starterProjects:
  - name: quarkus-quickstart
    description: minimal CRUD app with quarkus
    subDir: /getting-started/
    git:
      location: https://github.com/quarkusio/quarkus-quickstarts
      branch: master
      startPoint: 1.7.0.Final
----

[horizontal]
Key:: starterProjectObject
Type:: starterProjectObject
Required:: no
Description:: list of starter projects to be used

This starterProjects example uses Quarkus. For more information about the starterProjects in devfiles, see: xref:migrating-projects.adoc[].

== components

[source,yaml]
----
v2.0
---
components:
  - name: appsodyrun
    container:
      image: 'ajymau/java-openliberty-dev:latest'
      memoryLimit: 1512Mi
      mountSources: true
      endpoints:
        - name: 9080/tcp
          exposure: public
          public: true
          protocol: http
          targetPort: 9080
      env:
        - name: MODE2
          value: TEST2
        - name: myprop2
          value: myval2
      volumeMounts:
        - name: myvol
          path: /home/user/myvolpath
  - name: myvol
    volume:
      size: 3Gi
----

[horizontal]
Key:: componentObject
Type:: componentObject
Required:: no
Description:: list of components to be used

This component example uses an Open Liberty container. For more information about the components in devfiles, see: xref:migrating-components.adoc[].

== commands

[source,yaml]
----
v2.0
---
commands:
  - id: install
    exec:
      component: runtime
      commandLine: npm install
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: build
        isDefault: false
  - id: mkdir
    exec:
      component: runtime
      commandLine: mkdir /projects/testfolder
      workingDir: ${PROJECTS_ROOT}
  - id: run
    exec:
      component: runtime
      commandLine: npm start
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: run
        isDefault: true
  - id: buildAndMkdir
    composite:
         label: Build and Mkdir
         commands:
           - mkdir
           - install
         parallel: false
         group:
            kind: build
            isDefault: true
----

[horizontal]
Key:: commandObject
Type:: commandObject
Required:: no
Description:: command to be executed in an existing component container

This commands example uses an Open Liberty container. For more information about the commands in devfiles, see: xref:migrating-commands.adoc[].

== events

[source,yaml]
----
v2.0
---
commands:
  - id: copy
    exec:
      commandLine: "cp /tools/myfile.txt tools.txt"
      component: tools
      workingDir: /
  - id: initCache
    exec:
      commandLine: "./init_cache.sh"
      component: tools
      workingDir: /
  - id: connectDB
    exec:
      commandLine: "./connect_db.sh"
      component: runtime
      workingDir: /
  - id: disconnectDB
    exec:
      commandLine: "./disconnect_db.sh"
      component: runtime
      workingDir: /
  - id: cleanup
    exec:
      commandLine: "./cleanup.sh"
      component: tools
      workingDir: /
events:
  preStart:
    - "connectDB"
  postStart:
    - "copy"
    - "initCache"
  preStop:
    - "disconnectDB"
  postStop:
    - "cleanup"
----

[horizontal]
Key:: eventObject
Type:: eventObject
Required:: no
Description:: events to be executed during a project lifecycle

This events example uses an Open Liberty container. For more information about the events in devfiles, see: xref:adding-event-bindings.adoc[].

== Additional resources

* To start working on your own devfile, see xref:authoring-stacks.adoc[].
* For details on what makes a devfile, see xref:api-reference.adoc[].
