[id="proc_adding-attributes-to-a-devfile_{context}"]
= Adding attributes to a devfile

[role="_abstract"]
You can use devfile attributes to configure various features and properties according to user and tooling needs. Attributes are implementation-dependant, free-form YAML, and you can define attributes for the following devfile objects: `metadata`, `components`, `commands`, `projects`, and `starterProjects`.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]


.Procedure


. Define a custom attribute
+
When no editor is specified, a default editor is provided. To represent this user-defined example, use the `editorFree` attribute as shown in the following example:
+
.A devfile without an editor
====
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: petclinic-dev-environment
  attributes:
     editorFree: true
components:
  - name: myapp
    kubernetes:
      uri: my-app.yaml
----
====

[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
