[id="creating-a-git-repository_{context}"]
= Creating a Git repository

[role="_abstract"]
Set up a Git repository to store the devfile stacks to package into the devfile registry.

.Procedure

. Fork the link:https://github.com/devfile/registry[devfile/registry] repository.
. Name your forked repository.
. Add or remove any stacks you need from this repository.
. Create a `stacks/` directory for storing the devfile stacks. Each directory under `stacks/` must correspond to a specific stack, for example, `stacks/java-wildfly/`.
. To package any external devfile stacks or samples in your devfile registry, go to the root of your repository and create an `extraDevfileEntries.yaml` file.
. Add your devfile stacks to your `stacks/` directory.
. Verify every devfile stack contains at least one `devfile.yaml` file. Add other required files to the stacks. These files can include VSX plug-ins, Dockerfiles, or Kubernetes manifests.

The registry build tool automatically validates your customized registry.

[role="_additional-resources"]
.Additional resources

* Example of link:https://github.com/devfile/registry/blob/main/extraDevfileEntries.yaml[extraDevfileEntries.yaml].
* To create devfile stacks, see xref:creating-a-devfile-stack.adoc[].
