[id="proc_developing-with-devfiles_{context}"]
= Developing with devfiles
[role="_abstract"]

Use the devfile specification to develop a node.js “Hello World” application. Developing this application introduces you to how a devfile automates and simplifies your development process.

.Prerequisites

* To develop an application by using the devfile specification, you need to create a Kubernetes cluster on your local machine. To create such a cluster, install link:https://minikube.sigs.k8s.io/docs/start/[minikube start].
* To access your namespaces, download link:https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/[kubectl].
* To execute the devfile specification, install the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/cli_tools/developer-cli-odo#installing-odo[odo cli tool].

.Procedure

. Build your Kubernetes cluster by running `minikube start`.
. When you use minikube for the first time, you must enable Ingress to access your devfile projects. Enable Ingress by running `minikube addons enable ingress`.
. Confirm you are in the default namespace by running `kubectl get namespaces`.
. View the available devfiles by running `odo catalog list components`.
. Create a devfile project by running `odo create nodejs <name of your project> --starter`.
* Adding `--starter` tells odo to include the starter project currently inside the nodejs devfile specification, which makes it easier for you to develop an application.
. Run `odo push`. Doing so instructs odo to create the Kubernetes objects specified in the devfile.
. Run `kubectl get pod` to access your container.
. Run `minkube IP` to find your cluster IP address.
. Run `odo url create <name you give the url> --ingress --host <IP address>.nip.io`. Doing so creates an ingress inside your cluster that you can use to access your application using the cluster IP address.
* Example: `odo url create myfirstproject --ingress --host 192.168.64.2.nip.io`.
. Run `odo push` to build the URL.

.Verification steps

* To verify that you built your node.js "Hello World" application successfully, view the application in a web browser by copying and pasting the URL that was produced by running the `odo push` command. 
. Go the the URL and view your "Hello World" application.

.Additional resources

To continue working with devfiles, go to xref:using-devfiles.adoc[Using devfiles]
