[id="proc_adding-projects-to-a-devfile_{context}"]
= Adding projects to a devfile

[role="_abstract"]
This section describes how to add one or more projects to a devfile.


.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]


.Procedure

. Add a `projects` section in the devfile, containing a list of one or more projects.

+
.A minimal devfile with one single project
====
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: petclinic-dev-environment
  version: 2.0.0
projects:
  - name: petclinic
    git:
      remotes:
        origin: "https://github.com/spring-projects/spring-petclinic.git"
      checkoutFrom:
        revision: master
----
====
+
.A devfile with multiple projects
====
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: example-devfile
  version: 2.0.0
projects:
- name: frontend
  git:
    remotes:
      origin: "https://github.com/acmecorp/frontend.git"
- name: backend
  git:
    remotes:
      origin: "https://github.com/acmecorp/backend.git"
----
====

. For each project, define an unique value for the mandatory `name` attribute.



. For each project, define a mandatory source of either the `git` or `zip` type.

`git`:: Projects with sources in Git. `checkoutFrom` refers to the branch being used.
+
.Project-source type: git
====
[source,yaml]
----
projects:
  - name: my-project1
    git:
      remotes:
        origin: "https://github.com/my-org/project1.git"
      checkoutFrom:
        revision: master           <1>
----
====

`zip`:: Projects with sources in a ZIP archive. `location` refers to the URL of a ZIP file.
+
.Project-source type: zip
====
[source,yaml]
----
source:
    zip:
      location: http://host.net/path/project-src.zip
----
====


. For each project, define the optional `clonePath` attribute to specify the path into which the project is to be cloned. The path must be relative to the `/projects/` directory, and it cannot leave the `/projects/` directory. The default value is the project name.
+
.Defining the `clonePath` attribute
====
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
  version: 2.0.0
projects:
  - name: my-project-resource
    clonePath: resources/my-project
    zip:
    location: http://host.net/path/project-res.zip
  - name: my-project2
      git:
        remotes:
          origin: "https://github.com/my-org/project2.git"
        checkoutFrom:
          revision: develop
----
====

. For each project, define the optional `sparseCheckoutDir` attribute to populate the project sparsely with selected directories.
+
[NOTE]
====
* Set to `/my-module/` to create only the root `my-module` directory (and its content).

* Omit the leading slash (`my-module/`) to create all `my-module` directories that exist in the project. Including, for example, `/addons/my-module/`.
+
The trailing slash indicates that only directories with the given name (including their content) are created.

* Use wildcards to specify more than one directory name. For example, setting `module-*` checks out all directories of the given project that start with `module-`.

For more information, see link:https://git-scm.com/docs/git-read-tree#_sparse_checkout[Sparse checkout in Git documentation].

====

[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
