[id="proc_adding-plugin-component-to-a-devfile_{context}"]
= Adding `plug-in` component to a devfile

[role="_abstract"]
This section describes how to add a `plug-in` component to a devfile.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-components-to-a-devfile.adoc[]

.Procedure

. Define a component using the type `plug-in`.

. Define the `id` attribute. For the name and version of the plug-in, go to the plug-in registry. To find available {prod-short} plug-ins and more information about their registry, go to the GitHub repository, link:https://github.com/eclipse/che-plugin-registry[{prod-short} plug-in registry].
+
.Defining a plug-in `id`
====
[source,yaml]
----
  components:
   - name: exec-plug-in
     plug-in:
      id: machine-exec-plug-in/0.0.1
----
====

. Optional: Specify an alternative component registry using the `registryUrl` parameter:
+
.Defining a plug-in `id` and an alternative component registry
====
[source,yaml]
----
  components:
   - name: exec-plug-in
     plug-in:
      id: machine-exec-plug-in/0.0.1
      registryUrl: https://my-customregistry.com
----
====

. Optional: Provide a direct link to the component descriptor using the `reference` attribute instead of the `id` attribute. Typically, the component descriptor is named `meta.yaml`.
+
.Defining a plug-in with a direct link to the component descriptor
====
[source,yaml]
----
  components:
   - name: exec-plug-in
     plug-in:
      reference: https://raw.githubusercontent.com.../plug-in/1.0.1/meta.yaml
----
====
+
NOTE: You can never mix the `id` and `reference` attributes in a single component definition because they are mutually exclusive.

. Optional: Provide the plug-in component configuration using the `preferences` attribute:
+
.Configuring JVM using plug-in preferences
====
[source,yaml]
----
  id: redhat/java/0.38.0
  plug-in:
    preferences:
       java.jdt.ls.vmargs: '-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication'
----
====
+
.Configuring preferences as an array
====
[source,yaml]
----
  id: redhat/java/0.38.0
  plug--in:
    preferences:
      go.lintFlags: ["--enable-all", "--new"]
----
====


[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
