[id="deploying-a-devfile-registry-with-operator-lifecycle-manager_{context}"]
= Deploying a devfile registry with Operator Lifecycle Manager

[role="_abstract"]
When you have Operator Lifecycle Manager (OLM) installed on your cluster, use the devfile registry Operator to install and deploy a devfile registry.

.Procedure

. Install the devfile registry Operator:
.. Install link:https://github.com/operator-framework/operator-lifecycle-manager[OLM].
.. Download and install the link:https://mirror.openshift.com/pub/openshift-v4/clients/operator-sdk/latest/[operator-sdk CLI].
.. Run the `operator-sdk` command to install the devfile registry Operator:
+
[subs="+quotes"]
----
$ operator-sdk run bundle quay.io/devfile/registry-operator-bundle:next
----
+
. Deploy the devfile registry:
.. On an OpenShift cluster, run:
+
[subs="+quotes"]
----
$ cat <<EOF | oc apply -f -
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  name: devfile-registry
spec:
  devfileIndexImage: quay.io/devfile/devfile-index:next
EOF
----
+
.. On a Kubernetes cluster, run:
+
[subs="+quotes"]
----
$ cat <<EOF | kubectl apply -f -
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  name: devfile-registry
spec:
  devfileIndexImage: quay.io/devfile/devfile-index:next
 	tls:
    enabled: false
  k8s:
    ingressDomain: $INGRESS_DOMAIN
EOF
----

[NOTE]
====
Regardless of the cluster, if you are deploying your own devfile registry, change the `devfileIndexImage` field to the container image that you built.
====

[role="_additional-resources"]
.Additional resources

* For information on installing the devfile registry Operator, see link:https://github.com/devfile/registry-operator[devfile registry Operator].
* For information on installing OLM on your Kubernetes cluster, see the link:https://olm.operatorframework.io/docs/getting-started/[OLM quick start guide].
