[id="proc_adding-a-command-section-to-a-devfile_{context}"]
= Adding a command section to a devfile
[role="_abstract"]

Specify the commands you want to execute in your workspace.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-projects-to-a-devfile.adoc[]

.Procedure

. Add a `commands` section to a devfile that contains a list of one or more commands.

. For each command, define a unique value for the mandatory `id` attribute.

. For each command, define a mandatory type of one of the following types:

* `exec`
* `apply`
* `composite`

+
.Sample command
[source,yaml]
----
 commands:
   - id: build
     exec:
      component: mysql
      commandLine: mvn clean
      workingDir: /projects/spring-petclinic
----

. Define attributes for the `exec` command to run using the default shell in the container.
+
 * A `commandLine` attribute that is a command to execute.
 * A `component` attribute that specifies the container in which to execute the command.
+
[source,yaml]
----
schemaVersion: 2.1.0
metadata:
  name: mydevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      remotes:
        origin: "https://github.com/acme/my-go-project.git"
components:
  - name: go-cli
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      env:
        - name: GOPATH
          value: $(PROJECTS_ROOT)/go
        - name: GOCACHE
          value: /tmp/go-cache
commands:
  - id: compile and run
    exec:
      component: go-cli
      commandLine: "go get -d && go run main.go"
      workingDir: "${PROJECTS_ROOT}/src/github.com/acme/my-go-project"
----
+
[NOTE]

* A command can have only one action, though you can use `composite` commands to execute several commands either in sequence or in parallel.
