[id="proc_developing-with-devfiles_{context}"]
= Developing with devfiles
[role="_abstract"]

Use the devfile specification to develop a Node.js “Hello World” application. Developing this application introduces you to how a devfile automates and simplifies your development process.

.Prerequisites

To make developing with the devfile specification easier, consider doing the following:

* Install link:https://minikube.sigs.k8s.io/docs/start/[minikube] to create a Kubernetes cluster on your local machine.
* Download link:https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/[kubectl] to access your namespace.
* Enable link:https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/[ingress on minikube] to access your devfile project.
* Install the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/cli_tools/developer-cli-odo#installing-odo[odo command line interface (CLI) tool] to execute the devfile specification.

.Procedure

. View the available devfiles:
+
----
$ odo catalog list components
----
. Run `odo create nodejs _<name of your project>_ --starter` to create a devfile project.
* Add the `--starter` parameter to include the starter project currently inside the Node.js devfile specification, which makes it easier for you to develop an application.
. Run `minikube IP` to find your cluster IP address.
. Run `odo url create _<name you give the url>_ --ingress --host _<IP address>_.nip.io`. Doing so creates an ingress inside your cluster that you can use to access your application using the cluster IP address.
* Example: `odo url create myfirstproject --ingress --host 192.168.64.2.nip.io`.
. Run `odo push` to build the URL.

.Verification

* To verify that you built your Node.js "Hello World" application successfully, view the application in a web browser by copying and pasting the URL that was produced by running the `odo push` command. Go to the URL and view your "Hello World" application.

.Additional resources

To continue working with devfiles, go to xref:authoring-devfiles.adoc[Authoring devfiles].
