[id="proc_adding-a-kubernetes-or-openshift-component-to-a-devfile_{context}"]
= Adding a Kubernetes or Openshift component to a devfile

[role="_abstract"]
You can add either a `kubernetes` or `openshift` component to a devfile. Doing so enables you to configure your devfile to your unique development needs.

.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]
* xref:adding-components-to-a-devfile.adoc[]

.Procedure

. Define a component using the `kubernetes` or `openshift` property.

. Provide the content through the `uri` or `inlined` property.
+
.Adding an `openshift` component using the `uri` property
====
[source,yaml]
----
  components:
    - name: mysql
      openshift:
        uri: petclinic.yaml
----
====
+
.Adding a `kubernetes` component using the `inlined` property
====
[source,yaml]
----
  components:
  - name: myk8deploy
    kubernetes:
      inlined: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
        spec:
          template:
            spec:
              containers:
              - name: job
                image: myimage
                command: ["some",  "command"]
              restartPolicy: Never
----
====
+
. Specify the endpoint through the endpoint property with `kubernetes` or `openshift` components.

. Associate `kubernetes` or `openshift` components with `Apply` commands. If you do not associate `Apply` commands, they are assumed to be applied at start up.
+
