[id="proc_refering-to-a-parent-devfile-in-a-devfile_{context}"]
= Refering to a parent devfile in a devfile

[role="_abstract"]
.Prerequisites

* xref:adding-schema-version-to-a-devfile.adoc[]
* xref:adding-a-name-to-a-devfile.adoc[]


This section teaches you how to specify a parent devfile. You can choose a devfile and refer to another devfile as its parent. If you specify a parent, the child devfile inherits all its behavior from its parent devfile. Still, you can use the child devfile to override certain content from the parent devfile. If you override the correct content, you can reuse the same parent devfile in multiple other devfiles. If you do reuse a parent devfile, the parent turns into a stack that is used in multiple other devfiles.



You can refer to a parent devfile in three different ways:

* registry

* uri

* kubernetes

.Parent referred by registry
====
Using its `id` if it has been published in a registry.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    id: redhat/nodejs
    registry: https://devfile-registry.io/
----
====

.Parent referred by uri
====
Using the URI if it has been published on a static http server (like gist or pastebin).

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    uri: https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/nodejs/devfile.yaml
----
====

.Parent identified by a Kubernetes resource
====
Using a Kubernetes resource name and namespace if it has been deployed on a Kubernete cluster.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    kubernetes:
        name: mydevworkspacetemplate
        namespace: mynamespace
----
====

[role="_additional-resources"]
.Additional resources

* xref:api-reference.adoc[]
* xref:devfile-samples.adoc[]
