---
# Copyright (c) 2021 Red Hat, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Configuration file for the `htmltest` tool.
# The `htmltest` tool is validating the internal and external links on the HTML build of the documentation.
# See: https://github.com/wjdp/htmltest

DirectoryPath: build/
OutputDir: .cache/htmltest
ExternalTimeout: 60 # (seconds) default is 15.
IgnoreURLs:
  - http://0.0.0.0:4000
  - https://cse.google.com/cse.js
  - https://devfile.io/docs
  - https://github.com/devfile/docs/edit/
