---
asciidoc:
  attributes:
    context: devfile
    che-prod: Eclipse Che
    che-prod-short: Che
    che-prod-id-short: che
    che-prod-ver: 7.20
    prod: Devfile
    prod-short: Devfile
    prod-id-short: devfile
content:
  sources:
    - branches: HEAD
      start_path: docs
      url: ./
output:
  destinations:
    - clean: true
      path: out/docs
      provider: fs
runtime:
  cache_dir: ./.cache/antora
site:
  robots: allow
  start_page: devfile::index.adoc
  title: Devfile Documentation
  # url: Disabled on purpose in the development playbook to avoid htmltest crawling the live website.
ui:
  bundle:
    snapshot: true
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
urls:
  # html_extension_style: indexify
  redirect_facility: static
