= Devfile
:description: Software Defined Development Environments

Devfiles are YAML files that describe and define an environment in Che, including the source code and development components, like IDE tools and application runtimes. Che uses these devfiles to make a cloud workspace composed of multiple containers.

Within your devfile workspace, you can create multiple projects. In the components of the project, like the editor, plugin, or environment, the devfile commands build, test, and run your application. Also, any number of workspaces can be created from the same devfile. This way, workspaces can be shared and worked on by different teams. So now you can easily transfer, collaborate and expand your work.

Visit the following documentation to learn how to work with devfiles:

== API Reference

See link:{attachmentsdir}/api-reference.html[Devfile API Reference].


== Guide for Stacks Authors

See xref:assembly_making-a-workspace-portable-using-a-devfile.adoc[Guide for Stack Authors].


== v1 to v2 Migration Guide

See xref:migration_guide.adoc[Devfile v2 Migration Guide].


== Devfile v2.0 Examples

See https://github.com/devfile/api/tree/master/samples/devfiles[Devfile Samples].

== Additional Resources

For a visual and audible demonstration of devfiles, see the YouTube video, https://youtu.be/vnsLwtRz--w[Customize your own online IDE with a devifle].
