= Devfile v2 Migration Guide
:description: A guide to migrate a v1 Devfile to v2

This guide explains how to migrate an existing v1.0 devfile to v2.0.

== Schema Version

Attribute `apiVersion` has been renamed `schemaVersion`:

[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
apiVersion: 1.0.0
metadata:
  name: che-in-che-out
----
|
[source,yaml]
----
v2.0
---
schemaVersion: 2.0.0
metadata:
  name: che-in-che-out
----
|====

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/7[corresponding issue].

== How to migrate projects

There are NO major changes in the `projects` section of the devfile. A project specified in a v1.0 devfile will work as it is in a devfile v2.0. The only major change is the addition of a new kind of project: `starterProjects`. Those are supposed to be used in interactive mode only (user pick one) and the git repo get not be cloned but only source code get copied (kind of what `git archive --remote=<repository URL> | tar -t` would do).

=== starterProjects and projects description

[source,yaml]
----
v2.0
---
starterProjects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/42[corresponding issue].

== How to migrate components

There ARE major changes in the `components` section of the devfile. A component specified in a v1.0 devfile will NOT work as it is in a devfile v2.0.

=== Component is a polymophic type

For a better syntax validation component now is defined as a polymorphic type and can be implemented as `container`, `kubernetes`, `openshift`, `plugin` or `volume`.

[source,yaml]
----
v2.0
---
components:
  - container:
        image: maven
        ...
  - container:
        image: nodejs
        ...
  - kubernetes:
       reference: https://.../mongo.yaml
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/4[corresponding issue].

=== Shared Volumes Across Components

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/19[corresponding issue].

=== Out of Main Pod Compoenents

Details can be found in the  https://github.com/devfile/kubernetes-api/issues/48[corresponding issue].

=== Replace Alias with Name

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/9[corresponding issue].

=== Renaming dockerimage component type

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/8[corresponding issue].

=== Specify sources path for containers

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/17[corresponding issue].

=== Specify size of volume for component

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/14[corresponding issue].

=== Containers endpoints (routes/ingresses)

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/33[corresponding issue].

== How to migrate plugins

There ARE major changes about the definition of plugins in a devfile. Plugins are now specified using a devfile. A plugin specified in a v1.0 meta.yaml will NOT work as it is in a devfile v2.0.

[source,yaml]
----
v2.0
---
java8.yaml
---
schemaVersion: 2.0.0
metadata:
  publisher: redhat
  name: java8
  version: 0.57.0
  displayName: Language Support for Java 8
  title: Language Support for Java(TM) by ...
  description: Java Linting, Intellisense ...
  icon: https://.../logo-eclipseche.svg
  repository: https://github.../vscode-java
  category: Language
  firstPublicationDate: "2020-02-20"
  pluginType: che-theia-vsx # <== mandatory
                            # for plugins
                      # Valid types:               
                      #   che-theia-vsx
                      #   che-editor, 
                      #   che-theia-plugin,
                      #   che-theia-ext,
                      #   generic-service,
                      #   generic-ui
parent:
  id: redhat/theia-vsx-template/latest
  components:
    - container:
       name: vsx-installer
       env:
        - name: VSX_LIST
          value: java-dbg.vsix,java.vsix
components:
 - kubernetes:
    name: ...
    reference: ...
 - container:
    image: ...che-sidecar-java
    name: vscode-java
    memoryLimit: "1500Mi"
    volumeMounts:
     - path: "/home/theia/.m2"
       name: m2
 - volume:
    name: m2
----

And then can be referenced from a distinct devfile:

[source,yaml]
----
v2.0
---
devfile.yaml
---
components:
- plugin:
    name: java language server
    id: redhat/java11/0.57.0 # other then by `id`, a plugin
                             # can be referenced by `uri` and 
                             # `kubernetes`
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/31[corresponding issue].

== How to migrate commands

There ARE major changes in the `commands` section of the devfile. A command specified in a v1.0 devfile will NOT work as it is in a devfile v2.0.

=== Command Groups: build,run,test,debug

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/27[corresponding issue].

=== Apply Command

Details can be found in the https://github.com/devfile/kubernetes-api/issues/56[corresponding issue].

=== Environment Varibables for a Specific Command

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/21[corresponding issue].

=== Renaming workdir into workingDir

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/22[corresponding issue].

=== Id and label for Composite Commands

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/18[corresponding issue].

=== Run exec Commands as Specific User

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/34[corresponding issue].

=== Devfile metadata: add a link to an external website

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/38[corresponding issue].

=== Stack/Devfile Matching Rules

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/40[corresponding issue].

== Using parent devfiles to build reusable stacks

One of the major changes in the 2.0.0 specification is the addition of the concept of parent. That allows refering a devfile (the parent) from a distinct devfile and makes it possible to reuse in multiple devfiles the same parent (the stack).

[source,yaml]
----
# v2.0
---
schemaVersion: 2.0.0
metadata:
  name: nodejs-app
parent:
    uri: https://(...)/nodejs/devfile.yaml # <--- Parent referenced by `uri`, registry `id`
                                           #      or `kubernetes` devworkspace
  components:                              # <--- Parent configuration can be customized
    - container:
         name: vsx-installer
         env:
            - name: VSX_LIST
               value: java-dbg.vsix,java.vsix
components:                               # <--- components are added to parent's components
  - container:
      name: tooling                       # <--- should not match the name of a parent component
      image: busybox
commands:                                 # <--- commands are added to parent's commands
   (...)
----

Details are in the https://github.com/che-incubator/devworkspace-api/issues/25[corresponding issue].

== Adding event bindings

There is a new root element in the devfile 2.0: events: 

[source,yaml]
----
# v2.0
---
components:
  - container:
      name: "copier"
      image: ''
  - container:
      name: "maven"
      image: ''
  - plugin:
      id: theia
Commands:
containerBuild:
reference: 
composite:
 
  - exec:
      name: "copyNeededFiles"
      component: "copier"
      commandLine: "cp somefile"
  - exec:
      name: "buildAll"
      component: "maven"
      commandLine: "mvn ..."
  - vsCodeTask:
      name: "openFile"
      component: "theia"
events:
  preStart:
    - "copyNeededFiles"
  postStart:
    - "buildAll"
    - "openFile"
----

Details are in the https://github.com/che-incubator/devworkspace-api/issues/32[corresponding issue].

== New metadata

In v2 of the devfile we have added some new metadata like `version` (this is the https://github.com/che-incubator/devworkspace-api/issues/10[corresponding issue]) and some mandatory metadata for plugins (this is the https://github.com/devfile/kubernetes-api/issues/31[corresponding issue]).



