= Migrating from devfile v1 to devfile v2
:description: A guide to migrate a v1 Devfile to v2

This guide explains how to migrate an existing v1.0 devfile to v2.0.

== Schema version

Attribute `apiVersion` has been renamed `schemaVersion`:

[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
apiVersion: 1.0.0
metadata:
  name: che-in-che-out
----
|
[source,yaml]
----
v2.0
---
schemaVersion: 2.0.0
metadata:
  name: che-in-che-out
----
|====

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/7[corresponding issue].

== Migrating projects

A project specified in a v1.0 devfile works as it is in a devfile v2.0. The only major change is the addition of a new kind of project: `starterProjects`. Those are supposed to be used in interactive mode only (user must pick one) and the Git repo cannot be cloned but only source code get copied (kind of what `git archive --remote=<repository URL> | tar -t` would do).

=== `starterProjects` and projects description

[source,yaml]
----
v2.0
---
starterProjects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/42[corresponding issue].

== Migrating components

A component specified in a v1.0 devfile will not work as it is in a devfile v2.0.

=== Component is a polymorphic type

For a better syntax validation component now is defined as a polymorphic type and can be implemented as `container`, `kubernetes`, `openshift`, `plugin` or `volume`.

[source,yaml]
----
v2.0
---
components:
  - container:
        image: maven
        ...
  - container:
        image: nodejs
        ...
  - kubernetes:
       reference: https://.../mongo.yaml
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/4[corresponding issue].

=== Shared volumes across components

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/19[corresponding issue].

=== Out of main pod components

Details can be found in the  https://github.com/devfile/api/issues/48[corresponding issue].

=== Replace alias with Name

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/9[corresponding issue].

=== Renaming `dockerimage` component type

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/8[corresponding issue].

=== Specifying sources path for containers

Details can be found in the  https://github.com/che-incubator/devworkspace-api/issues/17[corresponding issue].

=== Specifying volume size for components

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/14[corresponding issue].

=== Containers endpoints (routes/ingresses)

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/33[corresponding issue].

== Migrating plugins

There ARE major changes about the definition of plugins in a devfile. Plugins are now specified using a devfile. A plugin specified in a v1.0 meta.yaml will NOT work as it is in a devfile v2.0.

[source,yaml]
----
v2.0
---
java8.yaml
---
schemaVersion: 2.0.0
metadata:
  publisher: redhat
  name: java8
  version: 0.57.0
  displayName: Language Support for Java 8
  title: Language Support for Java(TM) by ...
  description: Java Linting, Intellisense ...
  icon: https://.../logo-eclipseche.svg
  repository: https://github.../vscode-java
  category: Language
  firstPublicationDate: "2020-02-20"
  pluginType: che-theia-vsx # <== mandatory
                            # for plugins
                      # Valid types:               
                      #   che-theia-vsx
                      #   che-editor, 
                      #   che-theia-plugin,
                      #   che-theia-ext,
                      #   generic-service,
                      #   generic-ui
parent:
  id: redhat/theia-vsx-template/latest
  components:
    - container:
       name: vsx-installer
       env:
        - name: VSX_LIST
          value: java-dbg.vsix,java.vsix
components:
 - kubernetes:
    name: ...
    reference: ...
 - container:
    image: ...che-sidecar-java
    name: vscode-java
    memoryLimit: "1500Mi"
    volumeMounts:
     - path: "/home/theia/.m2"
       name: m2
 - volume:
    name: m2
----

And then can be referenced from a distinct devfile:

[source,yaml]
----
v2.0
---
devfile.yaml
---
components:
- plugin:
    name: java language server
    id: redhat/java11/0.57.0 # other then by `id`, a plugin
                             # can be referenced by `uri` and 
                             # `kubernetes`
----

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/31[corresponding issue].

== Migrating commands

There ARE major changes in the `commands` section of the devfile. A command specified in a v1.0 devfile will NOT work as it is in a devfile v2.0.

=== Command Groups: build, run, test, debug

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/27[corresponding issue].

=== Applying command

Details can be found in the https://github.com/devfile/api/issues/56[corresponding issue].

=== Environment variables for a specific command

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/21[corresponding issue].

=== Renaming `workdir` into `workingDir`

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/22[corresponding issue].

=== `Id` and `label` for composite commands

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/18[corresponding issue].

=== Run exec Commands as Specific User

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/34[corresponding issue].

=== Devfile metadata: add a link to an external website

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/38[corresponding issue].

=== Stack/Devfile Matching Rules

Details can be found in the https://github.com/che-incubator/devworkspace-api/issues/40[corresponding issue].

== Using parent devfiles to build reusable stacks

One of the major changes in the 2.0.0 specification is the addition of the concept of parent. That allows referring a devfile (the parent) from a distinct devfile and makes it possible to reuse in multiple devfiles the same parent (the stack).

[source,yaml]
----
# v2.0
---
schemaVersion: 2.0.0
metadata:
  name: nodejs-app
parent:
    uri: https://(...)/nodejs/devfile.yaml # <--- Parent referenced by `uri`, registry `id`
                                           #      or `kubernetes` devworkspace
  components:                              # <--- Parent configuration can be customized
    - container:
         name: vsx-installer
         env:
            - name: VSX_LIST
               value: java-dbg.vsix,java.vsix
components:                               # <--- components are added to parent's components
  - container:
      name: tooling                       # <--- should not match the name of a parent component
      image: busybox
commands:                                 # <--- commands are added to parent's commands
   (...)
----

Details are in the https://github.com/che-incubator/devworkspace-api/issues/25[corresponding issue].

== Adding event bindings

There is a new root element in the devfile 2.0: events: 

[source,yaml]
----
# v2.0
---
components:
  - container:
      name: "copier"
      image: ''
  - container:
      name: "maven"
      image: ''
  - plugin:
      id: theia
Commands:
containerBuild:
reference: 
composite:
 
  - exec:
      name: "copyNeededFiles"
      component: "copier"
      commandLine: "cp somefile"
  - exec:
      name: "buildAll"
      component: "maven"
      commandLine: "mvn ..."
  - vsCodeTask:
      name: "openFile"
      component: "theia"
events:
  preStart:
    - "copyNeededFiles"
  postStart:
    - "buildAll"
    - "openFile"
----

Details are in the https://github.com/che-incubator/devworkspace-api/issues/32[corresponding issue].

== New metadata

In v2 of the devfile we have added some new metadata like `version` (this is the https://github.com/che-incubator/devworkspace-api/issues/10[corresponding issue]) and some mandatory metadata for plugins (this is the https://github.com/devfile/api/issues/31[corresponding issue]).

== The `exec` command requires a defined component

`exec` now must have a component explicitly defined.

[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
  - id: helloWorld
      exec:
        env:
          - name: "USER"
            value: "John Doe"
        commandLine: 'echo "Hello ${USER}"'
        component: build-tools
----
|
[source,yaml]
----
v2.0
---
  - id: helloWorld
    exec:
      component: "mycomponent"
      env:
        - name: "USER"
          value: "John Doe"
      commandLine: 'echo "Hello ${USER}"'
      component: build-tools
----
|====
Details are in the https://github.com/devfile/api/issues/152[corresponding issue]

== Support of multiple remotes for a Git project
Devfile v2 supports multiple remotes for a Git project.

.Example of a project with multiple remotes defined
[source,yaml]
----
projects:
  - name: project   
    git:
      remotes:
        origin: "https://github.com/amisevsk/web-nodejs-sample.git"
        upstream: "https://github.com/che-samples/web-nodejs-sample.git"
        gh-collaborator: "https://github.com/gh-collaborator/web-nodejs-sample.git"  
      checkoutFrom: <1> 
        revision: foo <2> 
        remote: upstream <3> 
----
<1> Mandatory if there is more than one remote
<2> The revision that should be used checked out. May be a branch name, tag or commit id. Default branch should be checked out if missing.
<3> The remote name should be used as init. Required if there are more than one remote configured.

More details are in the https://github.com/devfile/api/issues/104[corresponding issue].

== `name` and `id` moved to a top-level
[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
components:
  - container:
      name: tools
----
|
[source,yaml]
----
v2.0
---
components:
  - name: tools
    container:
----
|====

More details are in the https://github.com/devfile/api/issues/102[corresponding issue].

== `mountSources` are true by default
`mountSources` field is defined as `true` for all non-plugin components and components that do not set dedicatedPod to `true`.
More details are in the https://github.com/devfile/api/issues/75[corresponding issue].

== `hotReloadCapable` added to `exec` commands
`hotReloadCapable` defines whether the command is capable to reload itself when source code changes. If set to `true` the command will not be restarted and it is expected to handle file changes on its own. 
Default value is `false`.

More details are in the https://github.com/devfile/api/issues/64[corresponding issue].

== `CommandGroupType` has been renamed to `CommandGroupKind`
More details are in the https://github.com/devfile/api/issues/59[corresponding issue].
