= Migrating from devfile v1.0 to devfile v2.0
:description: A guide to migrate a v1.0 Devfile to v2.0

This guide explains how to migrate an existing v1.0 devfile to v2.0.

== Schema version

Attribute `apiVersion` has been renamed to `schemaVersion`:

[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
apiVersion: 1.0.0
metadata:
  name: che-in-che-out
----
|
[source,yaml]
----
v2.0
---
schemaVersion: 2.0.0
metadata:
  name: che-in-che-out
----
|====

For more details, see link:https://github.com/devfile/api/issues/7[Devfile should have a `schemaVersion` attribute].

== Migrating projects

A project specified in a v1.0 devfile works as is in a devfile v2.0. The only major change is the addition of a new kind of project: `starterProjects`. Those are supposed to be used in interactive mode only (user must pick one) and the Git repository cannot be cloned. Instead, only source code is to be copied (for example, `git archive --remote=_<repository URL>_ | tar -t`).

=== `starterProjects` and `projects` description

[source,yaml]
----
v2.0
---
starterProjects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
----

For more details, see link:https://github.com/devfile/api/issues/42[starterProjects and projects description].

== Migrating components

There are major changes in the `components` section of the devfile. A component specified in a v1.0 devfile does not work as is in a devfile v2.0.

=== Component is a polymorphic type

For better syntax validation, a component now is defined as a polymorphic type and can be implemented as `container`, `kubernetes`, `openshift`, `plugin`, or `volume`.

[source,yaml]
----
v2.0
---
components:
  - container:
        image: maven
        ...
  - container:
        image: nodejs
        ...
  - kubernetes:
       reference: https://.../mongo.yaml
----

For more details, see link:https://github.com/devfile/api/issues/4[Polymorphic component type UX in a devfile].

=== Shared volumes across components

For more details, see link:https://github.com/devfile/api/issues/19[Allow volumes to be shared across components].

=== Out of main pod components

For more details, see link:https://github.com/devfile/api/issues/48[Out of main pod containers].

=== Replace alias with name

For more details, see link:https://github.com/devfile/api/issues/9[Names field mandatory for k8s/openshift, optional for plugins].

=== Renaming `dockerimage` component type

For more details, see link:https://github.com/devfile/api/issues/8[Renaming dockerimage component type].

=== Specifying sources path for containers

For more details, see link:https://github.com/devfile/api/issues/17[Specify the source mapping path for component containers].

=== Specifying volume size for components

For more details, see link:https://github.com/devfile/api/issues/14[Allow the size of a component's volume to be specified in a Devfile].

=== Containers endpoints (routes/ingresses)

For more details, see link:https://github.com/devfile/api/issues/33[Containers endpoints (routes/ingresses)].

== Migrating plug-ins

Plug-ins are specified using a devfile. A plug-in specified in a v1.0 `meta.yaml` does not work as is in a devfile v2.0.

[source,yaml]
----
v2.0
---
java8.yaml
---
schemaVersion: 2.0.0
metadata:
  publisher: redhat
  name: java8
  version: 0.57.0
  displayName: Language Support for Java 8
  title: Language Support for Java(TM) by ...
  description: Java Linting, Intellisense ...
  icon: https://.../logo-eclipseche.svg
  repository: https://github.../vscode-java
  category: Language
  firstPublicationDate: "2020-02-20"
  pluginType: che-theia-vsx # <== mandatory
                            # for plugins
                      # Valid types:               
                      #   che-theia-vsx
                      #   che-editor, 
                      #   che-theia-plugin,
                      #   che-theia-ext,
                      #   generic-service,
                      #   generic-ui
parent:
  id: redhat/theia-vsx-template/latest
  components:
    - container:
       name: vsx-installer
       env:
        - name: VSX_LIST
          value: java-dbg.vsix,java.vsix
components:
 - kubernetes:
    name: ...
    reference: ...
 - container:
    image: ...che-sidecar-java
    name: vscode-java
    memoryLimit: "1500Mi"
    volumeMounts:
     - path: "/home/theia/.m2"
       name: m2
 - volume:
    name: m2
----

And then can be referenced from a distinct devfile:

[source,yaml]
----
v2.0
---
devfile.yaml
---
components:
- plugin:
    name: java language server
    id: redhat/java11/0.57.0 # other then by `id`, a plugin
                             # can be referenced by `uri` and 
                             # `kubernetes`
----

For more details, see link:https://github.com/devfile/api/issues/31[Better plugin mechanism].

== Migrating commands

There ARE major changes in the `commands` section of the devfile. A command specified in a v1.0 devfile will NOT work as it is in a devfile v2.0.

=== Command Groups: build, run, test, debug

For more details, see link:https://github.com/devfile/api/issues/27[Command group (application lifecycle)].

=== Applying command

For more details, see link:https://github.com/devfile/api/issues/56[New type of command to `apply` a component].

=== Environment variables for a specific command

For more details, see link:https://github.com/devfile/api/issues/21[Environment variables for a specific command].

=== Renaming `workdir` into `workingDir`

For more details, see link:https://github.com/devfile/api/issues/22[Renaming workdir into workingDir].

=== `Id` and `label` for composite commands

For more details, see link:https://github.com/devfile/api/issues/18[Composite commands label and id].

=== Run exec Commands as Specific User

For more details, see link:https://github.com/devfile/api/issues/34[Run exec commands as specified user].

=== Devfile metadata: add a link to an external website

For more details, see link:https://github.com/devfile/api/issues/38[Devfile metadata: add a link to an external website].

=== Stack/Devfile Matching Rules

For more details, see link:https://github.com/devfile/api/issues/40[Stacks/Devfile matching rules].

== Using parent devfiles to build reusable stacks

One of the major changes in the 2.0.0 specification is the addition of the concept of parent. That allows referring a devfile (the parent) from a distinct devfile and makes it possible to reuse in multiple devfiles the same parent (the stack).

[source,yaml]
----
# v2.0
---
schemaVersion: 2.0.0
metadata:
  name: nodejs-app
parent:
    uri: https://(...)/nodejs/devfile.yaml # <--- Parent referenced by `uri`, registry `id`
                                           #      or `kubernetes` devworkspace
  components:                              # <--- Parent configuration can be customized
    - container:
         name: vsx-installer
         env:
            - name: VSX_LIST
               value: java-dbg.vsix,java.vsix
components:                               # <--- components are added to parent's components
  - container:
      name: tooling                       # <--- should not match the name of a parent component
      image: busybox
commands:                                 # <--- commands are added to parent's commands
   (...)
----

Details are in the link:https://github.com/devfile/api/issues/25[Parent Devfiles].

== Adding event bindings

There is a new root element in the devfile 2.0: events: 

[source,yaml]
----
# v2.0
---
components:
  - container:
      name: "copier"
      image: ''
  - container:
      name: "maven"
      image: ''
  - plugin:
      id: theia
Commands:
containerBuild:
reference: 
composite:
 
  - exec:
      name: "copyNeededFiles"
      component: "copier"
      commandLine: "cp somefile"
  - exec:
      name: "buildAll"
      component: "maven"
      commandLine: "mvn ..."
  - vsCodeTask:
      name: "openFile"
      component: "theia"
events:
  preStart:
    - "copyNeededFiles"
  postStart:
    - "buildAll"
    - "openFile"
----

Details are in the link:https://github.com/devfile/api/issues/32[Add lifecycle bindings to bind commands to specific events].

== New metadata

Version 2 of the devfile adds new metadata, including `version` (see link:https://github.com/devfile/api/issues/10[The devfile schema/samples should have version and name]) and some mandatory metadata for plug-ins (see link:https://github.com/devfile/api/issues/31[Better plugin mechanism]).

== The `exec` command requires a defined component

`exec` now must have a component explicitly defined.

[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
  - name: helloWorld
      exec:
        env:
          - name: "USER"
            value: "John Doe"
        commandLine: 'echo "Hello ${USER}"'
        component: build-tools
----
|
[source,yaml]
----
v2.0
---
  - id: helloWorld
    exec:
      component: "mycomponent"
      env:
        - name: "USER"
          value: "John Doe"
      commandLine: 'echo "Hello ${USER}"'
      component: build-tools
----
|====
For more details, see link:https://github.com/devfile/api/issues/152[Exec command should make component required]

== Support of multiple remotes for a Git project
Devfile v2 supports multiple remotes for a Git project.

.Example of a project with multiple remotes defined
[source,yaml]
----
projects:
  - name: project   
    git:
      remotes:
        origin: "https://github.com/amisevsk/web-nodejs-sample.git"
        upstream: "https://github.com/che-samples/web-nodejs-sample.git"
        gh-collaborator: "https://github.com/gh-collaborator/web-nodejs-sample.git"  
      checkoutFrom: <1> 
        revision: foo <2> 
        remote: upstream <3> 
----
<1> Mandatory if there is more than one remote.
<2> The revision that should be used checked out. May be a branch name, tag, or commit id. Default branch should be checked out if missing.
<3> The remote name that should be used as init. Required if there are more than one remote configured.

For more details, see https://github.com/devfile/api/issues/104[Support multiple remotes for projects to support forking workflow].

== `name` and `id` moved to a top-level
[cols="1a,1a"]
|====
| 
[source,yaml]
----
v1.0
---
components:
  - container:
      name: tools
----
|
[source,yaml]
----
v2.0
---
components:
  - name: tools
    container:
----
|====

More details are in the https://github.com/devfile/api/issues/102[corresponding issue].

== `mountSources` are true by default

The `mountSources` field is defined as `true` for all non-plug-in components and components that do not set `dedicatedPod` to `true`.
For more details, see link:https://github.com/devfile/api/issues/75[mountsources default value for containers].

== `hotReloadCapable` added to `exec` commands

The `hotReloadCapable` fields defines whether the command is capable of reloading itself when source code changes. If set to `true`, the command is not restarted, and it is expected to handle file changes on its own. 
Default value is `false`.

For more details, see link:https://github.com/devfile/api/issues/64[configuration option to avoid unncessary restarts of process].

== `CommandGroupType` has been renamed to `CommandGroupKind`
For more details, see link:https://github.com/devfile/api/issues/59[Rename command group type].
