// Module included in the following assemblies:
//
// making-a-workspace-portable-using-a-devfile

[id="devfile-reference_{context}"]
= Devfile reference

This section contains devfile reference and instructions on how to use the various elements that devfiles consist of.

== Adding projects to a devfile

Usually a devfile contains one or more projects. A workspace is created to develop those projects. Projects are added in the `projects` section of devfiles.

Each project in a single devfile must have:

* Unique name
* Source specified

Project source consists of one of the following types: `git`, `github` and `zip`.

`git`:: Projects with sources in Git. The location points to a clone link.

`github`:: Same as `git` but for projects hosted on link:https://github.com/[GitHub] only. Use `git` for projects that do not use GitHub-specific features.

`zip`:: Projects with sources in a ZIP archive. Location points to a ZIP file.


=== Project-source type: git

[source,yaml]
----
source:
    git:
      location: https://github.com/eclipse/che.git
      startPoint: master           <1>
      tag: 7.2.0
      commitId: 36fe587
      branch: master
      sparseCheckoutDir: wsmaster  <2>
----
<1> `startPoint` is the general value for `tag`, `commitId`, and `branch`. The `startPoint`, `tag`, `commitId`, and `branch` parameters are mutually exclusive. When more than one is supplied, the following order is used: `startPoint`, `tag`, `commitId`, `branch`.
<2> `sparseCheckoutDir` the template for the sparse checkout Git feature. This is useful when only a part of a project (typically only a single directory) is needed.

.`sparseCheckoutDir` parameter settings
====
* Set to `/my-module/` to create only the root `my-module` directory (and its content).

* Omit the leading slash (`my-module/`) to create all `my-module` directories that exist in the project. Including, for example, `/addons/my-module/`.
+
The trailing slash indicates that only directories with the given name (including their content) are created.

* Use wildcards to specify more than one directory name. For example, setting `module-*` checks out all directories of the given project that start with `module-`.
====

For more information, see link:https://git-scm.com/docs/git-read-tree#_sparse_checkout[Sparse checkout in Git documentation].


=== Project-source type: zip

[source,yaml]
----
source:
    zip:
      location: http://host.net/path/project-src.zip
----


=== Project clone-path parameter: clonePath

The `clonePath` parameter specifies the path into which the project is to be cloned. The path must be relative to the `/projects/` directory, and it cannot leave the `/projects/` directory. The default value is the project name.

.Example devfile with projects
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
projects:
  - name: my-project-resourse
    clonePath: resources/my-project
    zip:
      location: http://host.net/path/project-res.zip
  - name: my-project
    source:
      git:
        location: https://github.com/my-org/project.git
        branch: develop
----

[id="refering-a-parent-devfile-in-a-devfile_{context}"]
== Refering a parent devfile in a devfile

It is possible to refer another devfile as a parent to a given devfile. If a parent is specified, the devfile will inherit all behaviour from the parent. Part of the content of the parent can be modified in the child devfile.

A parent devfile can be referenced in 3 different ways: `registry`, `uri` or `kubernetes`.  

=== Parent referred by registry
Using its `id` if it has been published in a registry.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    id: redhat/nodejs/11.6
    registry: https://devfile-registry.io/
----

=== Parent referred by uri
Using the URI if it has been published on a static http server (like gist or pastebin).

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    id: redhat/nodejs/11.6
    uri: https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/nodejs/devfile.yaml
----

=== Parent referred by registry
Using a Kubernetes resource name, namespace and selector if it has been deployed on a Kubernete cluster.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: my-project-dev
parent:
    kubernetes:
        name: mydevworkspacetemplate
        namespace: mynamespace
        selector: mykey=myvalue
----


[id="adding-components-to-a-devfile_{context}"]
== Adding components to a devfile

Each component in a single devfile must have a unique name.

=== Component type: cheEditor

Describes the editor used in the workspace by defining its `id`. A devfile can only contain one component of the `cheEditor` type.

[source,yaml]
----
components:
  - cheEditor:
      id: eclipse/che-theia/next
      alias: theia-editor
----

When `cheEditor` is missing, a default editor is provided along with its default plug-ins. The default plug-ins are also provided for an explicitly defined editor with the same `id` as the default one (even if it is a different version). Che-Theia is configured as default editor along with the *{prod-short} Machine Exec* plug-in.

To specify that a workspace requires no editor, use the xref:attribute-editorfree_{context}[`editorFree:true` attribute] in the devfile attributes.

=== Component type: chePlugin

Describes plug-ins in a workspace by defining their `id`. It is allowed to have several `chePlugin` components.

[source,yaml]
----
  components:
   - chePlugin:
      id: eclipse/che-machine-exec-plugin/0.0.1
      name: exec-plugin
----

Both types above use an ID, which is slash-separated publisher, name and version of plug-in from the {prod-short} Plug-in registry.

List of available {prod-short} plug-ins and more information about registry can be found in the link:https://github.com/eclipse/che-plugin-registry[{prod-short} plug-in registry] GitHub repository.

=== Specifying an alternative component registry

To specify an alternative registry for the `cheEditor` and `chePlugin` component types, use the `registryUrl` parameter:

[source,yaml]
----
  components:
   - chePlugin:
      id: eclipse/che-machine-exec-plugin/0.0.1
      name: exec-plugin
      registryUrl: https://my-customregistry.com
----

=== Specifying a component by linking to its descriptor

An alternative way of specifying `cheEditor` or `chePlugin`, instead of using the editor or plug-in `id` (and optionally an alternative registry), is to provide a direct link to the component descriptor (typically named `meta.yaml`) by using the `reference` field:

[source,yaml]
----
  components:
   - chePlugin:
      name: exec-plugin
      reference: https://raw.githubusercontent.com.../plugin/1.0.1/meta.yaml
----

NOTE: It is impossible to mix the `id` and `reference` fields in a single component definition; they are mutually exclusive.

=== Tuning chePlugin component configuration

A chePlugin component may need to be precisely tuned, and in such case, component preferences can be used. The example shows how to configure JVM using plug-in preferences.

[source,yaml]
----
  id: redhat/java/0.38.0
  chePlugin:
    preferences:
       java.jdt.ls.vmargs: '-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication'
----

Preferences may also be specified as an array:

[source,yaml]
----
  id: redhat/java/0.38.0
  chePlugin:
    preferences:
      go.lintFlags: ["--enable-all", "--new"]
----


=== Component type: kubernetes

A complex component type that allows to apply configuration from a list of Kubernetes or OpenShift components.

The content can be provided through the `reference` attribute, which points to the file with the component content.

[source,yaml]
----
  components:
    - kubernetes:
        name: mysql
        reference: petclinic.yaml
        selector:
          app.kubernetes.io/name: mysql
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: petclinic
----

Alternatively, to post a devfile with such components to REST API, the contents of the Kubernetes or OpenShift list can be embedded into the devfile using the `referenceContent` field:

[source,yaml]
----
  components:
    - kubernetes:
        name: mysql
        reference: petclinic.yaml
        referenceContent: |
             kind: List
             items:
              -
               apiVersion: v1
               kind: Pod
               metadata:
                name: ws
               spec:
                containers:
               ... etc
----

=== Overriding container entrypoints

As with the xref:component-type-dockerimage_{context}[`dockerimage` component], it is possible to override the entrypoint of the containers contained in the Kubernetes or OpenShift list using the `command` and `args` properties (as link:https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes[understood] by Kubernetes).

There can be more containers in the list (contained in Pods or Pod templates of deployments). To select which containers to apply the entrypoint changes to.

The entrypoints can be defined as follows:

[source,yaml]
----
  components:
    - kubernetes:
        name: appDeployment
        reference: app-deployment.yaml
        entrypoints:
        - parentName: mysqlServer
          command: ['sleep']
          args: ['infinity']
        - parentSelector:
          app: prometheus
          args: ['-f', '/opt/app/prometheus-config.yaml']
----

The `entrypoints` list contains constraints for picking the containers along with the `command` and `args` parameters to apply to them. In the example above, the constraint is `parentName: mysqlServer`, which will cause the command to be applied to all containers defined in any parent object called `mysqlServer`. The parent object is assumed to be a top level object in the list defined in the referenced file, which is `app-deployment.yaml` in the example above.

Other types of constraints (and their combinations) are possible:

`containerName`:: the name of the container
`parentName`:: the name of the parent object that (indirectly) contains the containers to override
`parentSelector`:: the set of labels the parent object needs to have

A combination of these constraints can be used to precisely locate the containers inside the referenced Kubernetes list.

=== Overriding container environment variables

To provision or override entrypoints in a Kubernetes or OpensShift component, configure it in the following way:

[source,yaml]
----
  components:
    - kubernetes:
        name: appDeployment
        reference: app-deployment.yaml
        env:
          - name: ENV_VAR
            value: value
----

This is useful for temporary content or without access to editing the referenced content. The specified environment variables are provisioned into each init container and containers inside all Pods and Deployments.

=== Specifying mount-source option

To specify a project sources directory mount into container(s), use the `mountSources` parameter:

[source,yaml]
----
   components:
      - kubernetes:
          name: appDeployment
          reference: app-deployment.yaml
          mountSources: true
----

If enabled, project sources mounts will be applied to every container of the given component.
This parameter is also applicable for `chePlugin` type components.

[id="component-type-container{context}"]
=== Component type: container

A component type that allows to define a container image-based configuration of a container in a workspace. A devfile can contain one or more component(s) of the `container` type. The `container` type of component brings in custom tools into the workspace. The component is identified by its image.

[source,yaml]
----
 components:
   - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      volumeMounts:
        - name: mavenrepo
          path: /root/.m2
       env:
         - name: ENV_VAR
           value: value
       endpoints:
         - name: maven-server
           targetPort: 3101
           configuration:
             protocol: tcp
             scheme: http
             secure: 'true'
             public: 'true'
             discoverable: 'false'
       memoryLimit: 1536M
       command: ['tail']
       args: ['-f', '/dev/null']
----

*Example of a minimal `container` component*

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
    name: MyDevfile
components:
  - container:
      name: go
      image: golang
      memoryLimit: 512Mi
      command: ['sleep', 'infinity']
----

It specifies the type of the component, `container` and the `image` attribute names the image to be used for the component using the usual Docker naming conventions, that is, the above `image` attribute is equal to `docker.io/library/golang:latest`.

A `container` component has many features that enable augmenting the image with additional resources and information needed for meaningful integration of the *tool* provided by the image with {prod}.

==== Mounting project sources

For the `container` component to have access to the project sources, you must set the `mountSources` attribute to `true`.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
    name: MyDevfile
components:
  - container:
      name: go
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
----

The sources is mounted on a location stored in the `CHE_PROJECTS_ROOT` environment variable that is made available in the running container of the image. This location defaults to `/projects`. If `sourceMapping` is defined in the container, it overrides the 'CHE_PROJECT_ROOT' value if present and mounts the source to the path defined by `sourceMapping`.

==== Container Entrypoint

The `command` attribute of the `container` along with other arguments, is used to modify the `entrypoint` command of the container created from the image. In {prod} the container is needed to run indefinitely so that you can connect to it and execute arbitrary commands in it at any time. Because the availability of the `sleep` command and the support for the `infinity` argument for it is different and depends on the base image used in the particular images, {prod-short} cannot insert this behavior automatically on its own. However, you can take advantage of this feature to, for example, start up necessary servers with modified configurations, etc.

=== Persistent Storage

Components of any type can specify the custom volumes to be mounted on specific locations within the image. Note that the volume names are shared across all components and therefore this mechanism can also be used to share file systems between components.

Example specifying volumes for `container` type:

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
components:
  - container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: cache
          path: /.cache
----

Example specifying volumes for `cheEditor`/`chePlugin` type:

[source,yaml]
----
scheamVersion: 2.0.0
metadata:
  name: MyDevfile
components:
  - cheEditor:
      name: theia-editor
      id: eclipse/che-theia/next
      env:
      - name: HOME
        value: $(CHE_PROJECTS_ROOT)
      volumeMounts:
      - name: cache
        path: /.cache
----

Example specifying volumes for `kubernetes`/`openshift` type:

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
components:
  - openshift:
      name: mongo
      reference: mongo-db.yaml
      volumeMounts:
      - name: mongo-persistent-storage
        path: /data/db
----

=== Specifying container memory limit for components

To specify a container(s) memory limit for `container`, `chePlugin`, `cheEditor`, use the `memoryLimit` parameter:

[source,yaml]
----
  components:
   - chePlugin:
      name: exec-plugin
      id: eclipse/che-machine-exec-plugin/0.0.1
      memoryLimit: 1Gi
   - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      memoryLimit: 512M
----

This limit will be applied to every container of the given component.

For the `cheEditor` and `chePlugin` component types, RAM limits can be described in the plug-in descriptor file, typically named `meta.yaml`.

If none of them are specified, system-wide defaults will be applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB]` system property).


=== Specifying container memory request for components

To specify a container(s) memory request for `chePlugin` or  `cheEditor`, use the `memoryRequest` parameter:

[source,yaml]
----
  components:
   - chePlugin:
      name: exec-plugin
      id: eclipse/che-machine-exec-plugin/0.0.1
      memoryLimit: 1Gi
      memoryRequest: 512M
   - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      memoryLimit: 512M
      memoryRequest: 256M
----

This limit will be applied to every container of the given component.

For the `cheEditor` and `chePlugin` component types, RAM requests can be described in the plug-in descriptor file, typically named `meta.yaml`.

If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__REQUEST__MB]` system property).


=== Specifying container CPU limit for components

To specify a container(s) CPU limit for `chePlugin`, `cheEditor` or `container` use the `cpuLimit` parameter:

[source,yaml]
----
  components:
   - chePlugin:
      name: exec-plugin
       id: eclipse/che-machine-exec-plugin/0.0.1
       cpuLimit: 1.5
   - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      cpuLimit: 750m
----

This limit will be applied to every container of the given component.

For the `cheEditor` and `chePlugin` component types, CPU limits can be described in the plug-in descriptor file, typically named `meta.yaml`.

If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES]` system property).


=== Specifying container CPU request for components

To specify a container(s) CPU request for `chePlugin`, `cheEditor` or `container` use the `cpuRequest` parameter:

[source,yaml]
----
  components:
   - chePlugin:
      name: exec-plugin
      id: eclipse/che-machine-exec-plugin/0.0.1
      cpuLimit: 1.5
      cpuRequest: 0.225
   - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      cpuLimit: 750m
      cpuRequest: 450m
----

This limit will be applied to every container of the given component.

For the `cheEditor` and `chePlugin` component types, CPU requests can be described in the plug-in descriptor file, typically named `meta.yaml`.

If none of them are specified, system-wide defaults are applied (see description of `pass:[CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES]` system property).

=== Environment variables

{prod} allows you to configure Docker containers by modifying the environment variables available in component's configuration.
Environment variables are supported by the following component types: `container`, `chePlugin`, `cheEditor`, `kubernetes`, `openshift`.
In case component has multiple containers, environment variables will be provisioned to each container.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
components:
  - container:
      name: go
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      env:
        - name: GOPATH
          value: $(CHE_PROJECTS_ROOT)/go
  - cheEditor:
      name: theia-editor
      id: eclipse/che-theia/next
      memoryLimit: 2Gi
      env:
      - name: HOME
        value: $(CHE_PROJECTS_ROOT)
----

[NOTE]
====
* The variable expansion works between the environment variables, and it uses the Kubernetes convention for the variable references.

* The predefined variables are available for use in custom definitions.
====

The following environment variables are pre-set by the {prod-short} server:

* `CHE_PROJECTS_ROOT`: The location of the projects directory (note that if the component does not mount the sources, the projects will not be accessible).

* `CHE_WORKSPACE_LOGS_ROOT__DIR`: The location of the logs common to all the components. If the component chooses to put logs into this directory, the log files are accessible from all other components.

* `CHE_API_INTERNAL`: The URL to the {prod-short} server API endpoint used for communication with the {prod-short} server.

* `CHE_WORKSPACE_ID`: The ID of the current workspace.

* `CHE_WORKSPACE_NAME`: The name of the current workspace.

* `CHE_WORKSPACE_NAMESPACE`: The {prod-short} namespace of the current workspace. This environment variable is the name of the user or organization that the workspace belongs to. Note that this is different from
the Kubernetes namespace or OpenShift project to which the workspace is deployed.

* `CHE_MACHINE_TOKEN`: The token used to authenticate the request against the {prod-short} server.

* `CHE_MACHINE_AUTH_SIGNATURE__PUBLIC__KEY`: The public key used to secure the communication with the {prod-short} server.

* `CHE_MACHINE_AUTH_SIGNATURE__ALGORITHM`: The encryption algorithm used in the secured communication with the {prod-short} server.

A devfiles may only need the `CHE_PROJECTS_ROOT` environment variable to locate the cloned projects in the component's container. More advanced devfiles might use the `CHE_WORKSPACE_LOGS_ROOT__DIR` environment variable to read the logs (for example as part of a devfile command). The environment variables used to securely access the {prod-short} server are mostly out of scope for devfiles and are present only for advanced use cases that are usually handled by the {prod-short} plug-ins.

=== Endpoints

Components of any type can specify the endpoints that the Docker image exposes. These endpoints can be made accessible to the users if the {prod-short} cluster is running using a Kubernetes ingress or an OpenShift route and to the other components within the workspace. You can create an endpoint for your application or database, if your application or database server is listening on a port and you want to be able to directly interact with it yourself or you want other components to interact with it.

Endpoints have a number of properties as shown in the following example:

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      location: https://github.com/acme/my-go-project.git
components:
  - container:
      name: go
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      env:
        - name: GOPATH
          value: $(CHE_PROJECTS_ROOT)/go
        - name: GOCACHE
          value: /tmp/go-cache
      endpoints:
      - name: web
        targetPort: 8080
        configuration:
          discoverable: false
          public: true
          protocol: tcp
          scheme: http
  - container:
      name: postgres
      image: postgres
      memoryLimit: 512Mi
      env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: database
      endpoints:
        - name: postgres
          targetPort: 5432
          configuration:
            discoverable: true
            public: false
----

Here, there are two Docker images, each defining a single endpoint. Endpoint is an accessible port that can be made accessible inside the workspace or also publicly (example, from the UI). Each endpoint has a name and port, which is the port on which certain server running inside the container is listening. The following are a few attributes that you can set on the endpoint:

* `discoverable`: If an endpoint is discoverable, it means that it can be accessed using its name as the host name within the workspace containers (in the Kubernetes parlance, a service is created for it with the provided name).
55
* `public`: The endpoint will be accessible outside of the workspace, too (such endpoint can be accessed from the {prod-short} user interface). Such endpoints are publicized always on port `80` or `443` (depending on whether `tls` is enabled in {prod-short}).

* `protocol`: For public endpoints the protocol is a hint to the UI on how to construct the URL for the endpoint access. Typical values are `http`, `https`, `ws`, `wss`.

* `secure`: A boolean (defaulting to `false`) specifying whether the endpoint is put behind a JWT proxy requiring a JWT workspace token to grant access. The JWT proxy is deployed in the same Pod as the server and assumes the server listens solely on the local loopback interface, such as `127.0.0.1`.
+
WARNING: Listening on any other interface than the local loopback poses a security risk because such server is accessible without the JWT authentication within the cluster network on the corresponding IP addresses.

* `path`: The URL of the endpoint.

* `unsecuredPaths`: A comma-separated list of endpoint paths that are to stay unsecured even if the `secure` attribute is set to `true`.

* `cookiesAuthEnabled`: When set to `true` (the default is `false`), the JWT workspace token is automatically fetched and included in a workspace-specific cookie to allow requests to pass through the JWT proxy.
+
WARNING: This setting potentially allows a link:https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF] attack when used in conjunction with a server using POST requests.

When starting a new server within a component, {prod-short} autodetects this, and the UI offers to automatically expose this port as a `public` port. This is useful for debugging a web application, for example. It is impossible to do this for servers that autostart with the container (for example, a database server). For such components, specify the endpoints explicitly.

Example specifying endpoints for `kubernetes`/`openshift` and `chePlugin`/`cheEditor` types:

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
components:
  - cheEditor:
      name: theia-editor
      id: eclipse/che-theia/next
      endpoints:
      - name: 'theia-extra-endpoint'
        targetPort: 8880
        configuration:
          discoverable: true
          public: true

  - chePlugin:
      id: redhat/php/latest
      memoryLimit: 1Gi
      endpoints:
      - name: 'php-endpoint'
        targetPort: 7777

  - chePlugin:
      name: theia-editor
      id: eclipse/che-theia/next
      endpoints:
      - name: 'theia-extra-endpoint'
        targetPort: 8880
        configuration:
          discoverable: true
          public: true

  - openshift:
      name: webapp
      reference: webapp.yaml
      endpoints:
      - name: 'web'
        targetPort: 8080
        configuration:
          discoverable: false
          public: true
          protocol: http

  - openshift:
      name: mongo
      reference: mongo-db.yaml
      endpoints:
      - name: 'mongo-db'
        targetPort: 27017
        configuration:
          discoverable: true
          public: false
----

=== Kubernetes and OpenShift resources

Complex deployments can be described using Kubernetes or OpenShift resource lists that can be referenced in the devfile. This makes them a part of the workspace.

[IMPORTANT]
====
* Because a {prod-short} workspace is internally represented as a single deployment, all resources from the Kubernetes or OpenShift list are merged into that single deployment.

* Be careful when designing such lists because this can result in name conflicts and other problems.

* Only the following subset of the Kubernetes objects are supported: `deployments`, `pods`, `services`, `persistent volume claims`, `secrets`, and `config maps`. Kubernetes Ingresses are ignored, but OpenShift routes are supported. A workspace created from a devfile using any other object types fails to start.

* When running {prod-short} on a Kubernetes cluster, only Kubernetes lists are supported. When running {prod-short} on an OpenShift cluster, both Kubernetes and OpenShift lists are supported.
====

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      location: https://github.com/acme/my-go-project.git
components:
  -  kubernetes:
      reference: ../relative/path/postgres.yaml
----

The preceding component references a file that is relative to the location of the devfile itself. Meaning, this devfile is only loadable by a {prod-short} factory to which you supply the location of the devfile and therefore it is able to figure out the location of the referenced Kubernetes resource list.

The following is an example of the `postgres.yaml` file.

[source,yaml]
----
apiVersion: v1
kind: List
items:
-
    apiVersion: v1
    kind: Deployment
    metadata:
        name: postgres
        labels:
            app: postgres
    spec:
        template:
        metadata:
            name: postgres
            app:
                name: postgres
        spec:
            containers:
            - image: postgres
              name: postgres
              ports:
              - name: postgres
                containerPort: 5432
                volumeMounts:
                - name: pg-storage
                  mountPath: /var/lib/postgresql/data
            volumes:
            - name: pg-storage
              persistentVolumeClaim:
                  claimName: pg-storage
-
    apiVersion: v1
    kind: Service
    metadata:
        name: postgres
        labels:
            app: postgres
            name: postgres
    spec:
        ports:
            - port: 5432
              targetPort: 5432
        selector:
            app: postgres
-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: pg-storage
      labels:
        app: postgres
    spec:
        accessModes:
         - ReadWriteOnce
        resources:
            requests:
                storage: 1Gi
----

For a basic example of a devfile with an associated Kubernetes or OpenShift list, see link:https://github.com/redhat-developer/devfile/tree/master/samples/web-nodejs-with-db-sample[web-nodejs-with-db-sample] on redhat-developer GitHub.

If you use generic or large resource lists from which you will only need a subset of resources, you can select particular resources from the list using a selector (which, as the usual Kubernetes selectors, works on the labels of the resources in the list).

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      location: https://github.com/acme/my-go-project.git
components:
  - kubernetes:
      reference: ../relative/path/postgres.yaml
      selector:
        app: postgres
----

Additionally, it is also possible to modify the entrypoints (command and arguments) of the containers present in the resource list. For details of the advanced use case, see the reference (TODO: link).

== Adding commands to a devfile

A devfile allows to specify commands to be available for execution in a workspace. Every command can contain a subset of actions, which are related to a specific component in whose container it will be executed.

[source,yaml]
----
 commands:
   - exec:
      id: build
      component: mysql
      commandLine: mvn clean
      workingDir: /projects/spring-petclinic
----

You can use commands to automate the workspace. You can define commands for building and testing your code, or cleaning the database.

The following are two kinds of commands:

* {prod-short} specific commands: You have full control over what component executes the command.

* Editor specific commands: You can use the editor-specific command definitions (example: `tasks.json` and `launch.json` in Che-Theia, which is equivalent to how these files work in VS Code).

=== {prod-short}-specific commands

Each {prod-short}-specific command features:

 * An `commandLine` attribute that is a command to execute.
 * A `component` attribute that specifies the container in which to execute the command.
 
 The commands are run using the default shell in the container.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      location: https://github.com/acme/my-go-project.git
components:
  - container:
      name: go-cli
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      env:
        - name: GOPATH
          value: $(CHE_PROJECTS_ROOT)/go
        - name: GOCACHE
          value: /tmp/go-cache
commands:
  - exec:
      id: compile and run
      component: go-cli
      commandLine: “go get -d && go run main.go”
      workingDir: “${CHE_PROJECTS_ROOT}/src/github.com/acme/my-go-project”
      runAsUser: root
----
+
[NOTE]
====
* If a component to be used in a command must have an alias. This alias is used to reference the component in the command definition. Example: `alias: go-cli` in the component definition and `component: go-cli` in the command definition. This ensures that {prod} can find the correct container to run the command in.

* A command can have only one action.
====

=== Editor-specific commands

If the editor in the workspace supports it, the devfile can specify additional configuration in the editor-specific format. This is dependent on the integration code present in the workspace editor itself and so is not a generic mechanism. However, the default Che-Theia editor within {prod} is equipped to understand the `tasks.json` and `launch.json` files provided in the devfile.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      location: https://github.com/acme/my-go-project.git
commands:
  - vscode-task:
      name: tasks
      referenceContent: >
          {
              "version": "2.0.0",
              "tasks": [
                  {
                      "label": "create test file",
                      "type": "shell",
                      "command": "touch ${workspaceFolder}/test.file"
                  }
              ]
          }
----

This example shows association of a `tasks.json` file with a devfile. Notice the `vscode-task` type that instructs the Che-Theia editor to interpret this command as a tasks definition and `referenceContent` attribute that contains the contents of the file itself. You can also save this file separately from the devfile and use `reference` attribute to specify a relative or absolute URL to it.

In addition to the `vscode-task` commands, the Che-Theia editor understands `vscode-launch` type using which you can specify the launch configurations.

=== Command group

A given command can be assigned to one or more groups that represents the nature of the command.  The support groups are: `build`, `run`, `test` and `debug`. For each of the groups, one default command can be defined in each group by specifying the `isDefault` value.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-maven-project
    clonePath: maven/src/github.com/acme/my-maven-project
    git:
      location: https://github.com/acme/my-maven-project.git
components:
  - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      mountSources: true
      command: ['tail']
commands:
  - exec:
      id: package
      component: maven
      commandLine: “mvn package”
      group: 
        kind: build
  - exec:
      id: install
      component: maven
      commandLine: “mvn install”
      group: 
        kind: build
        isDefault: true
----

=== Composite command

A composite command can be defined to chain multiple commands together. The individual commands that are called from a composite command can be referenced by the `name` of the command.  A `parallel` boolean can be specified to determine if the commands within a composite command are being executed sequentially or in parallel.

[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: MyDevfile
projects:
  - name: my-maven-project
    clonePath: maven/src/github.com/acme/my-maven-project
    git:
      location: https://github.com/acme/my-maven-project.git
components:
  - container:
      name: maven
      image: eclipe/maven-jdk8:latest
      mountSources: true
      command: ['tail']
commands:
  - exec:
      id: package
      component: maven
      commandLine: “mvn package”
      group: 
        kind: build
  - exec:
      id: install
      component: maven
      commandLine: “mvn install”
      group: 
        kind: build
        isDefault: true
  - composite:
      id: installAndPackage
      commands:
        - install
        - package
      parallel: false
----

=== Command preview URL

It is possible to specify a preview URL for commands that expose web UI. This URL is offered for opening when the command is executed.

[source,yaml]
----
commands:
    - exec:
        id: tasks
        previewUrl:
          port: 8080     <1>
          path: /myweb   <2>
        component: go-cli
        commandLine: "go run webserver.go"
        workingDir: ${CHE_PROJECTS_ROOT}/webserver
----
<1> TCP port where the application listens. Mandatory parameter.
<2> The path part of the URL to the UI. Optional parameter. The default is root (`/`).

The example above opens `++http://__<server-domain>__/myweb++`, where `_<server-domain>_` is the URL to the dynamically created Kubernetes Ingress or OpenShift Route.

==== Setting the default way of opening preview URLs

By default, a notification that asks the user about the URL opening preference is displayed. 

To specify the preferred way of previewing a service URL:

. Open {prod-short} preferences in *File -> Settings -> Open Preferences* and find `che.task.preview.notifications` in the *{prod-short}* section.

. Choose from the list of possible values:
+
* `on` -- enables a notification for asking the user about the URL opening preferences
* `alwaysPreview` -- the preview URL opens automatically in the *Preview* panel as soon as a task is running
* `alwaysGoTo` -- the preview URL opens automatically in a separate browser tab as soon as a task is running
* `off` -- disables opening the preview URL (automatically and with a notification)


== Devfile attributes

Devfile attributes can be used to configure various features.

[id="attribute-editorfree_{context}"]
=== Attribute: editorFree

When an editor is not specified in a devfile, a default is provided. When no editor is needed, use the `editorFree` attribute. The default value of `false` means that the devfile requests the provisioning of the default editor.

.Example of a devfile without an editor
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: petclinic-dev-environment
components:
  - kubernetes:
      name: myApp
      local: my-app.yaml
attributes:
  editorFree: true
----

=== Attribute: persistVolumes (ephemeral mode)

By default, volumes and PVCs specified in a devfile are bound to a host folder to persist data even after a container restart. To disable data persistence to make the workspace faster, such as when the volume back end is slow, modify the `persistVolumes` attribute in the devfile. The default value is `true`. Set to `false` to use `emptyDir` for configured volumes and PVC.

.Example of a devfile with ephemeral mode enabled
[source,yaml]
----
schemaVersion: 2.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    git:
      location: 'https://github.com/che-samples/web-java-spring-petclinic.git'
attributes:
  persistVolumes: false
----
