name: Preview Build

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install and Build
        run: |
          npm install -g @antora/cli
          yarn install
          yarn run generate-api-reference
          antora antora-playbook-for-development.yml

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: out/docs
          retention-days: 7

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt
