---
# Copyright (c) 2021 Red Hat, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
name: Devfile Docs Build
on:
  push:
    branches:
      - publication
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ["devfile/landing-page"]
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: build-and-deploy
